### ISSUE TITLE
How to get the accuracy of SDK

### ISSUE THREAD

**Issue by GanchengZhu** [visualcamp/seeso-sample-android#21]
Is there any progress on the accuracy of the models and the details of the model or the algorithm?
Where can I find the preprint paper?

**Comment by Dabin22** [comment]
@GanchengZhu Recent documents on model accuracy are published [here](https://medium.com/seeso-tech-blog/seeso-android-accuracy-test-a163edff73f7), and details or algorithms about the model are private.

**Comment by GanchengZhu** [comment]
Thanks very much for your kind response!

But I will warn you that your models and algorithms are not secure on your SDK. Your tflite models can be dumped by Frida.
