### ISSUE TITLE
CameraPosition usage by library

### ISSUE THREAD

**Issue by radkoff26** [visualcamp/seeso-sample-android#24]
Hey! I tried to run application using SeeSo on tablet with camera on longer axis. Compared to device with camera on shorter axis, accuracy perceptibly decreased. I was trying to find out how CameraPosition propagates screen size to GazeTracker. Eventually, after checking the code of the library I figured out that this CameraPosition I specified before starting gaze tracking had no impact on further library work. Besides `addCameraPosition(CameraPosition)`, I even tried to use `selectCameraPosition(int)` method to select my camera position somehow. However, nothing changed even after that - it kept using auto-defined screen size.
The question is: how can I affect on GazeTracker, so that it changes active screen area size which is used for gaze tracking?

How I used it:

```java
gazeTracker.addCameraPosition(cameraPosition)
gazeTracker.startTracking()
```

 - Device: Samsung SM-X700
 - OS: Android 13

**Comment by Dabin22** [comment]
Hello, @radkoff26 

First, in the camera position values, set the `cameraOnLongerAxis` value to `true`. For `originX` and `originY`, input the values measured based on the top left of the display when the camera is positioned at the top. After doing so, use the `selectCameraPosition` function after the `addCameraPosition` function to make your selection. It seems that the current device information has been added to the server, so I recommend checking that.

Thank you for using our service.

**Comment by radkoff26** [comment]
Thank you for your reply, @Dabin22!

Well, I'm starting to realize how it works but not really completely. Although I didn't find information about camera position of my device on your site, I'd like to find out how exactly I need to determine camera position origins on it.

Let's imagine that I have a device Samsung SM-X700. It has camera on its longer axis. Target orientation of this device is landscape, since its width is bigger than height when holding device with camera on its top side. I understand that I need to measure X-axis and Y-axis offsets (origins) from left top corner of screen to camera (according to information on site). After doing that I mentioned that accuracy completely decreased. Then I started to think around that probably in my case I should measure origins from camera to my device screen left bottom corner in landscape (in portrait, it would be exactly left top corner). Am I thinking right? Can you point my thoughts in right direction, please? And, by chance, can you share link to the page with devices camera positions list?

Thanks in advance!

**Comment by radkoff26** [comment]
By the way, I tested application using different devices with camera on shorter axis, and it worked just fine! There is just something about longer axis, I think.

**Comment by Dabin22** [comment]
@radkoff26 
The current server has the device information saved as:
"screen_origin_x": -119,
"screen_origin_y": -4,
"camera_on_longer_axis": true.
Currently, we are not providing a list of registered devices.

I hope this answers your question.

**Comment by radkoff26** [comment]
This resolved the problem! Thank you!
Closing issue as completed.
