### ISSUE TITLE
I have a problem running your repo. 

### ISSUE THREAD

**Issue by TREEANA** [visualcamp/seeso-sample-android#25]
I downloaded sdk and copied the extracted aar into correct project's folder. 

However  I encountered an error  like below image .  

![image](https://github.com/visualcamp/seeso-sample-android/assets/76998594/3dcaad45-0ea7-414f-aa1a-58d6949698cd)

Could you please help me verify if this code is working correctly?

**Comment by Dabin22** [comment]
@TREEANA  please provide more specific information and raise the issue again. 
ex) jdk, android studio, os, current seeso sdk version, build type.......
