### ISSUE TITLE
I have a problem running your repo (2)

### ISSUE THREAD

**Issue by TREEANA** [visualcamp/seeso-sample-android#26]
I downloaded sdk and copied the extracted aar into correct project's folder.

However I encountered an error like below image .

![image](https://github.com/visualcamp/seeso-sample-android/assets/76998594/6a7b952e-e649-47e2-9690-57ef2f5b7a2e)

Could you please help me verify if this code is working correctly?

Sry for not more specific information.

I attached detailed information below: 
            jdk : java version "11.0.19" 2023-04-18 LTS
            SDK: SeeSo.Android_3_1_2
            OS: window 11
            Android Studio : Android Studio Flamingo | (2022.2.1 Patch 2
                 Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
                 Runtime version: 17.0.6+0-b2043.56-9586694 amd64
                 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.)
           build type: debug for app and debug for view

**Comment by Dabin22** [comment]
adding the following line in gradle.properties:
```
org.gradle.jvmargs=-Xmx1536M \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
```

**Comment by TREEANA** [comment]
ty, It is worked.
